package cash.p.terminal.ui_compose.theme

import androidx.compose.ui.graphics.Color

internal val Dark = Color(0xFF13151A)
internal val SteelLight = Color(0xFFE1E1E5)
internal val Steel20 = Color(0x336E7899)

internal val StatusSuccessL = Color(0xFF15A65F)
internal val StatusSuccessD = Color(0xFF16C96F)
internal val StatusWarningL = Color(0xFFF29B00)
internal val StatusWarningD = Color(0xFFFFB52E)
internal val StatusErrorL = Color(0xFFCC3030)
internal val StatusErrorD = Color(0xFFFF4D4D)
internal val BrandD = Color(0xFF4A98E9)
internal val BrandL = Color(0xFF4692DA)
internal val BaseD = Color(0xFF0F0F0F)
internal val BaseL = Color(0xFFF0EFEB)
internal val NavigationD = Color(0xFF000000)
internal val NavigationL = Color(0xFFFBFAF7)
internal val OverlayL = Color(0xFF0F0F0F).copy(alpha = 0.48f)
internal val OverlayD = Color(0xFF000000).copy(alpha = 0.64f)
internal val SurfaceD = Color(0xFF18181A)
internal val SurfaceElevatedD = Color(0xFF2A2A2D)
internal val ActionBackgroundD = Color(0xFF2A2A2D)
internal val ActionBackgroundL = Color(0xFFEBEAE6)
internal val ActionBorderD = Color(0xFF3A3A3E)
internal val ActionBorderL = Color(0xFFD8D7D2)
internal val BorderDefaultD = Color(0xFF3A3A3A)
internal val BorderDefaultL = Color(0xFFD2D1CC)
internal val BorderDividerD = Color(0xFF2F2F32)
internal val BorderDividerL = Color(0xFFE2E1DD)
internal val SecondaryFilledBackgroundD = Color(0xFF242424)
internal val SecondaryFilledBorderD = Color(0xFF3A3A3A)
internal val SecondaryFilledBorderL = Color(0xFFD0CFCA)
internal val TextPrimaryD = Color(0xFFF5F5F6)
internal val TextPrimaryL = Color(0xFF171719)
internal val TextSecondaryD = Color(0xFF94949A)
internal val TextSecondaryL = Color(0xFF686D76)
internal val TextDisabledD = Color(0xFF66666C)
internal val TextDisabledL = Color(0xFF9A9DA4)
internal val OutlineBorderL = Color(0xFF85888F)
