package cash.p.terminal.ui_compose.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class Colors(
    val backgroundBase: Color,
    val backgroundNavigation: Color,
    val backgroundOverlay: Color,
    val surfacePrimary: Color,
    val surfaceElevated: Color,
    val surfacePlaceholder: Color,
    val controlActionBackground: Color,
    val controlActionBorder: Color,
    val controlTrack: Color,
    val brandDefault: Color,
    val statusSuccess: Color,
    val statusWarning: Color,
    val statusError: Color,
    val statusSuccess20: Color,
    val statusWarning20: Color,
    val statusError20: Color,
    val statusSuccess50: Color,
    val statusWarning50: Color,
    val statusError50: Color,
    val borderDefault: Color,
    val borderDivider: Color,
    val borderAccentSubtle: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textSecondaryDimmed: Color,
    val textDisabled: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val iconDisabled: Color,
    val buttonPrimaryBrandContent: Color,
    val buttonPrimaryNeutralBackground: Color,
    val buttonPrimaryNeutralContent: Color,
    val buttonPrimaryDestructiveBackground: Color,
    val buttonPrimaryDestructiveContent: Color,
    val buttonPrimaryDisabledBackground: Color,
    val buttonPrimaryOutlineContent: Color,
    val buttonPrimaryOutlineBorder: Color,
    val buttonSecondaryFilledBackground: Color,
    val buttonSecondaryFilledBorder: Color,
    val badgeBackground: Color,
    val contentInverse: Color,
    val switchThumbChecked: Color,
    val switchThumbUnchecked: Color,
    val switchTrackUnchecked: Color,
    val qrBackground: Color,
    val scannerBackground: Color,
    val snackbarNeutralBackground: Color,
    val contentOnColor: Color,
    val transparent: Color = Color.Transparent,
)
