package cash.p.terminal.ui_compose.theme

import androidx.compose.material3.ColorScheme

fun Colors.toMaterialColorScheme() = ColorScheme(
    primary = brandDefault,
    onPrimary = buttonPrimaryBrandContent,
    primaryContainer = surfacePrimary,
    onPrimaryContainer = textPrimary,
    inversePrimary = brandDefault,
    secondary = statusSuccess,
    onSecondary = buttonPrimaryBrandContent,
    secondaryContainer = surfacePrimary,
    onSecondaryContainer = textPrimary,
    tertiary = brandDefault,
    onTertiary = contentInverse,
    tertiaryContainer = surfacePrimary,
    onTertiaryContainer = textPrimary,
    background = backgroundBase,
    onBackground = textPrimary,
    surface = surfacePrimary,
    onSurface = textPrimary,
    surfaceVariant = badgeBackground,
    onSurfaceVariant = textPrimary,
    surfaceTint = brandDefault,
    inverseSurface = textPrimary,
    inverseOnSurface = contentInverse,
    error = statusError,
    onError = contentInverse,
    errorContainer = surfacePrimary,
    onErrorContainer = textPrimary,
    outline = borderDefault,
    outlineVariant = borderDivider,
    scrim = backgroundOverlay,
    surfaceBright = surfacePrimary,
    surfaceDim = backgroundBase,
    surfaceContainer = surfacePrimary,
    surfaceContainerHigh = surfaceElevated,
    surfaceContainerHighest = surfaceElevated,
    surfaceContainerLow = surfacePrimary,
    surfaceContainerLowest = backgroundBase,
    primaryFixed = statusWarning,
    primaryFixedDim = brandDefault,
    onPrimaryFixed = buttonPrimaryBrandContent,
    onPrimaryFixedVariant = surfacePrimary,
    secondaryFixed = statusSuccess,
    secondaryFixedDim = statusSuccess,
    onSecondaryFixed = buttonPrimaryBrandContent,
    onSecondaryFixedVariant = surfacePrimary,
    tertiaryFixed = brandDefault,
    tertiaryFixedDim = brandDefault,
    onTertiaryFixed = contentInverse,
    onTertiaryFixedVariant = textPrimary,
)
