import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    id("com.android.kotlin.multiplatform.library")
    id(libs.plugins.kotlin.parcelize.get().pluginId)
    id(libs.plugins.devtools.ksp.get().pluginId)
}

// KMP source directories must be configured explicitly or Detekt reports NO-SOURCE.
detekt {
    source.setFrom(
        "src/commonMain/kotlin",
        "src/androidMain/kotlin",
        "src/desktopMain/kotlin",
    )
}

kotlin {
    android {
        namespace = "cash.p.terminal.wallet.market"
        compileSdk = rootProject.ext.get("compile_sdk_version") as Int
        minSdk = rootProject.ext.get("min_sdk_version") as Int
        androidResources.enable = true

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
            freeCompilerArgs.addAll(
                "-P",
                "plugin:org.jetbrains.kotlin.parcelize:additionalAnnotation=io.horizontalsystems.core.common.CommonParcelize",
            )
        }

        withHostTest {
            isIncludeAndroidResources = true
        }
    }

    jvm("desktop") {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    sourceSets {
        commonMain {
            dependencies {
                api(project(":core:common"))
                implementation(project(":core:network"))

                implementation(libs.room.runtime)
                // Public ABI: the favorites DataStore and its platform migration are injected.
                api(libs.datastore.preferences.core)

                implementation(libs.rxjava)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.coroutines.rx2)

                implementation(libs.retrofit)
                implementation(libs.retrofit.gson)
                implementation(libs.retrofit.scalars)
                implementation(libs.retrofit.rxjava2)
                implementation(libs.gson)
                implementation(libs.okhttp.logging.interceptor)

                implementation(project.dependencies.platform(libs.koin.bom))
                implementation(libs.koin.core)
                implementation(libs.kermit)
            }
        }
        androidMain {
            dependencies {
                implementation(libs.koin.android)
                implementation(libs.android.core.ktx)
            }
        }
        // One physical copy of the initial coins dump: Android assets, desktop classpath resources.
        getByName("desktopMain") {
            resources.srcDir("src/androidMain/assets")
            dependencies {
                implementation(libs.sqlite.bundled)
            }
        }
        getByName("desktopTest") {
            dependencies {
                implementation(libs.kotlin.test.junit)
            }
        }
        getByName("androidHostTest") {
            dependencies {
                implementation(project(":core:network"))
                implementation(libs.junit)
                implementation(libs.mockk)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.robolectric)
                implementation(libs.androidx.test.core)
                implementation(libs.kotlin.test.junit)
                implementation(libs.koin.android)
            }
        }
    }
}

// Room rejects blocking DAO functions unless android.content.Context is visible to the processor.
// The DAOs are shared with Android, so KSP gets a bare marker type; it is never packaged.
val roomAndroidMarker = java.sourceSets.create("roomAndroidMarker") {
    java.setSrcDirs(listOf("room-android-marker/java"))
}

dependencies {
    "desktopMainCompileOnly"(roomAndroidMarker.output)
    add("kspAndroid", libs.room.compiler)
    add("kspDesktop", libs.room.compiler)
}

// The initial coins dump is regenerated by InitialCoinsListGenerator only when the flag is passed.
tasks.withType<Test>().configureEach {
    systemProperty("updateCoinsList", (project.findProperty("updateCoinsList") ?: "false").toString())
}

// The desktop data directory comes from XDG_DATA_HOME/APPDATA when set, and from user.home
// otherwise. Dropping the two variables leaves user.home as the single knob the tests redirect.
tasks.named<Test>("desktopTest") {
    setEnvironment(environment.filterKeys { it != "XDG_DATA_HOME" && it != "APPDATA" })
}
